workflows:
  ios-testflight:
    name: iOS TestFlight Deployment

    integrations:
      app_store_connect: Codemagic Final Key

    max_build_duration: 60
    instance_type: mac_mini_m1

    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: "main"
          include: true
          source: true

    environment:
      xcode: latest
      cocoapods: default

      vars:
        BUNDLE_ID: "com.tooyakov.x5lite"
        XCODE_PROJECT: "x5lite.xcodeproj"
        XCODE_SCHEME: "x5lite"

      # МЫ УБРАЛИ РУЧНЫЕ ФАЙЛЫ. Теперь Codemagic сам решит, что качать.
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.tooyakov.x5lite"

    scripts:
      - name: Fetch signing files (force download)
        script: |
          keychain initialize
          # Эта команда сама скачает рабочий сертификат и профиль напрямую из Apple
          # Она игнорирует битые файлы в настройках Codemagic
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Create export options
        script: |
          cat > $CM_BUILD_DIR/export_options.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>teamID</key><string>F8LA8PC4U6</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.tooyakov.x5lite</key>
              <string>X5LITE_PROFILE_FINAL</string>
            </dict>
          </dict>
          </plist>
          PLIST

      - name: Build IPA
        script: |
          xcodebuild \
            -project x5lite.xcodeproj \
            -scheme x5lite \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build.xcarchive \
            archive

          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/build.xcarchive \
            -exportPath $CM_BUILD_DIR/build \
            -allowProvisioningUpdates \
            -exportOptionsPlist $CM_BUILD_DIR/export_options.plist

    artifacts:
      - build/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
        submit_to_app_store: false

      email:
        recipients:
          - veagledesign@gmail.com
        notify:
          success: true
          failure: true
