workflows:
  ios-testflight:
    name: iOS TestFlight Deployment

    integrations:
      app_store_connect: Codemagic Final Key

    max_build_duration: 60
    instance_type: mac_mini_m1

    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: "main"
          include: true
          source: true

    environment:
      xcode: latest
      cocoapods: default

      vars:
        BUNDLE_ID: "com.tooyakov.x5lite"
        XCODE_PROJECT: "x5lite.xcodeproj"
        XCODE_SCHEME: "x5lite"

      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.tooyakov.x5lite"

    scripts:
      - name: Fetch signing files (create profiles) + apply
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
        submit_to_app_store: false

      email:
        recipients:
          - veagledesign@gmail.com
        notify:
          success: true
          failure: true
