workflows:
  ios-testflight:
    name: iOS TestFlight Deployment
    integrations:
      app_store_connect: Codemagic Fresh
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.x5pro.app
      vars:
        XCODE_PROJECT: "x5lite.xcodeproj"
        XCODE_SCHEME: "x5lite"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set build number
        script: |
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    
    publishing:
      email:
        recipients:
          - veagledesign@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
        submit_to_app_store: false
