workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    environment:
      xcode: 15.0
      cocoapods: default
    scripts:
      - name: Show project structure
        script: |
          echo "Project structure:"
          ls -la
          echo "\nSwift files:"
          find . -name "*.swift"
      
      - name: Create basic Xcode project
        script: |
          echo "Note: This is a Swift source code repository."
          echo "To build this project, you need to:"
          echo "1. Open Xcode on a Mac"
          echo "2. Create a new iOS App project"
          echo "3. Copy these Swift files into the project"
          echo "4. Configure signing and capabilities"
          echo ""
          echo "Files available:"
          find x5lite -name "*.swift" -o -name "*.plist" -o -name "*.entitlements"
    
    artifacts:
      - "**/*.swift"
      - "**/*.plist"
      - "**/codemagic.yaml"
    
    publishing:
      email:
        recipients:
          - veagledesign@gmail.com
        notify:
          success: true
          failure: true
